require: rubocop-rspec


AllCops:
  TargetRubyVersion: 2.7.2
  Exclude:
    - 'thrift/**/*'
  NewCops: enable

Style/Documentation:
  Enabled: no

Style/IfUnlessModifier:
  Enabled: no

RSpec/NestedGroups:
  Max: 4

RSpec/ExampleLength:
  Enabled: no

RSpec/MessageSpies:
  Enabled: no

RSpec/MultipleExpectations:
  Enabled: no

RSpec/MultipleMemoizedHelpers:
  Enabled: no

Metrics/BlockLength:
  Enabled: no

Metrics/MethodLength:
  Enabled: no

Metrics/AbcSize:
  Enabled: no

Metrics/ClassLength:
  Enabled: no

Metrics/ParameterLists:
  Enabled: no

Lint/UnusedMethodArgument:
  Enabled: no

Style/FrozenStringLiteralComment:
  Enabled: yes
  EnforcedStyle: always
  Include:
    - 'lib/**/*'

Metrics/LineLength:
  Max: 120

Style/SingleLineMethods:
  Enabled: false
